In [33]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import os
from pathlib import Path
import matplotlib.pyplot as plt
import numpy as np

from data_norm_pipeline import pipeline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

# Handle Dataset 1

In [ ]:
data_1_class_labels = '../../data/1erDataset/dyslexia_class_label.csv'
df_class_labels = pd.read_csv(data_1_class_labels)
df_class_labels.head()

   subject_id  class_id         label
0        1003         0  non-dyslexic
1        1016         0  non-dyslexic
2        1019         0  non-dyslexic
3        1033         0  non-dyslexic
4        1040         0  non-dyslexic

In [35]:
for index, subject in df_class_labels.iterrows():
    subject_id = subject[0]
    # print(subject_id)
    data_1_path = f'../1erDataset/data/Subject_{subject_id}_T4_Meaningful_Text_raw.csv'
    df = pipeline.load_dataset1(data_1_path)
    df.to_csv(f"../NormDataset/subject_{subject_id}_clean.csv", index=False)

# Handle Dataset 2

In [ ]:
data_2_class_labels = '../../data/2emeDataset/All/subjects.csv'
df_2_class_labels = pd.read_csv(data_2_class_labels, index_col=0)
df_2_class_labels.head()

  subject_id  class_id    label
0     726PT3         0  Control
1     772AK3         0  Control
2     713PE4         0  Control
3     796NT3         0  Control
4     753PJ3         0  Control

In [ ]:
for index, subject in df_2_class_labels.iterrows():
    subject_id = subject[0]
    # print(subject_id)
    data_2_path = f'../../data/2emeDataset/All/{subject_id}.csv'
    df = pipeline.load_dataset2(data_2_path)
    df.to_csv(f"../subject_{subject_id}_clean.csv", index=False)

# Handle App subject

In [ ]:
data_app_path = f'../../data/AppDataset/gaze_log(1).csv'
df = pipeline.load_app(data_app_path)
df.to_csv(f"../subject_app_clean.csv", index=False)

# Create subjects class label

In [39]:
df_class_labels

    subject_id  class_id         label
0         1003         0  non-dyslexic
1         1016         0  non-dyslexic
2         1019         0  non-dyslexic
3         1033         0  non-dyslexic
4         1040         0  non-dyslexic
..         ...       ...           ...
65        1903         1      dyslexic
66        1913         1      dyslexic
67        1929         1      dyslexic
68        1993         1      dyslexic
69        1996         1      dyslexic

[70 rows x 3 columns]

In [43]:
df_2_class_labels

    subject_id  class_id     label
0       726PT3         0   Control
1       772AK3         0   Control
2       713PE4         0   Control
3       796NT3         0   Control
4       753PJ3         0   Control
..         ...       ...       ...
180     512LM1         1  Dyslexic
181     774HJ2         1  Dyslexic
182     795SJ1         1  Dyslexic
183     725MF1         1  Dyslexic
184     312BE1         1  Dyslexic

[185 rows x 3 columns]

In [44]:
df_2_class_labels['label'] = df_2_class_labels['label'].map({
    'Control': 'non-dyslexic'
}).fillna('dyslexic')

In [45]:
result = pd.concat([df_class_labels, df_2_class_labels])
result

    subject_id  class_id         label
0         1003         0  non-dyslexic
1         1016         0  non-dyslexic
2         1019         0  non-dyslexic
3         1033         0  non-dyslexic
4         1040         0  non-dyslexic
..         ...       ...           ...
180     512LM1         1      dyslexic
181     774HJ2         1      dyslexic
182     795SJ1         1      dyslexic
183     725MF1         1      dyslexic
184     312BE1         1      dyslexic

[255 rows x 3 columns]

In [47]:
result['label'].value_counts()

label
dyslexic        132
non-dyslexic    123
Name: count, dtype: int64

In [ ]:
result.to_csv(f"../dyslexia_class_label.csv", index=False)